//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesDAO.ServiceABI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Collaborateur", Namespace="http://schemas.datacontract.org/2004/07/ABIEnCouches")]
    [System.SerializableAttribute()]
    public partial class Collaborateur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiviliteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatriculeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomCollabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomCollabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituationFamilialeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Actif {
            get {
                return this.ActifField;
            }
            set {
                if ((this.ActifField.Equals(value) != true)) {
                    this.ActifField = value;
                    this.RaisePropertyChanged("Actif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Civilite {
            get {
                return this.CiviliteField;
            }
            set {
                if ((object.ReferenceEquals(this.CiviliteField, value) != true)) {
                    this.CiviliteField = value;
                    this.RaisePropertyChanged("Civilite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Matricule {
            get {
                return this.MatriculeField;
            }
            set {
                if ((this.MatriculeField.Equals(value) != true)) {
                    this.MatriculeField = value;
                    this.RaisePropertyChanged("Matricule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCollab {
            get {
                return this.NomCollabField;
            }
            set {
                if ((object.ReferenceEquals(this.NomCollabField, value) != true)) {
                    this.NomCollabField = value;
                    this.RaisePropertyChanged("NomCollab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrenomCollab {
            get {
                return this.PrenomCollabField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomCollabField, value) != true)) {
                    this.PrenomCollabField = value;
                    this.RaisePropertyChanged("PrenomCollab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SituationFamiliale {
            get {
                return this.SituationFamilialeField;
            }
            set {
                if ((object.ReferenceEquals(this.SituationFamilialeField, value) != true)) {
                    this.SituationFamilialeField = value;
                    this.RaisePropertyChanged("SituationFamiliale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContratType", Namespace="http://schemas.datacontract.org/2004/07/ABIEnCouches")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClassesDAO.ServiceABI.Cdi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClassesDAO.ServiceABI.ContratTemporaire))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClassesDAO.ServiceABI.Cdd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClassesDAO.ServiceABI.Stagiaire))]
    public partial class ContratType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateDebutContratField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FinReelContratField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdContratField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaireContractuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateDebutContrat {
            get {
                return this.DateDebutContratField;
            }
            set {
                if ((this.DateDebutContratField.Equals(value) != true)) {
                    this.DateDebutContratField = value;
                    this.RaisePropertyChanged("DateDebutContrat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FinReelContrat {
            get {
                return this.FinReelContratField;
            }
            set {
                if ((this.FinReelContratField.Equals(value) != true)) {
                    this.FinReelContratField = value;
                    this.RaisePropertyChanged("FinReelContrat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContrat {
            get {
                return this.IdContratField;
            }
            set {
                if ((this.IdContratField.Equals(value) != true)) {
                    this.IdContratField = value;
                    this.RaisePropertyChanged("IdContrat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qualification {
            get {
                return this.QualificationField;
            }
            set {
                if ((object.ReferenceEquals(this.QualificationField, value) != true)) {
                    this.QualificationField = value;
                    this.RaisePropertyChanged("Qualification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalaireContractuel {
            get {
                return this.SalaireContractuelField;
            }
            set {
                if ((this.SalaireContractuelField.Equals(value) != true)) {
                    this.SalaireContractuelField = value;
                    this.RaisePropertyChanged("SalaireContractuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutField, value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cdi", Namespace="http://schemas.datacontract.org/2004/07/ABIEnCouches")]
    [System.SerializableAttribute()]
    public partial class Cdi : ClassesDAO.ServiceABI.ContratType {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContratTemporaire", Namespace="http://schemas.datacontract.org/2004/07/ABIEnCouches")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClassesDAO.ServiceABI.Cdd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClassesDAO.ServiceABI.Stagiaire))]
    public partial class ContratTemporaire : ClassesDAO.ServiceABI.ContratType {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateFinContratField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotifField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateFinContrat {
            get {
                return this.DateFinContratField;
            }
            set {
                if ((this.DateFinContratField.Equals(value) != true)) {
                    this.DateFinContratField = value;
                    this.RaisePropertyChanged("DateFinContrat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motif {
            get {
                return this.MotifField;
            }
            set {
                if ((object.ReferenceEquals(this.MotifField, value) != true)) {
                    this.MotifField = value;
                    this.RaisePropertyChanged("Motif");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cdd", Namespace="http://schemas.datacontract.org/2004/07/ABIEnCouches")]
    [System.SerializableAttribute()]
    public partial class Cdd : ClassesDAO.ServiceABI.ContratTemporaire {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stagiaire", Namespace="http://schemas.datacontract.org/2004/07/ABIEnCouches")]
    [System.SerializableAttribute()]
    public partial class Stagiaire : ClassesDAO.ServiceABI.ContratTemporaire {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EcoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MissionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ecole {
            get {
                return this.EcoleField;
            }
            set {
                if ((object.ReferenceEquals(this.EcoleField, value) != true)) {
                    this.EcoleField = value;
                    this.RaisePropertyChanged("Ecole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mission {
            get {
                return this.MissionField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionField, value) != true)) {
                    this.MissionField = value;
                    this.RaisePropertyChanged("Mission");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceABI.IServiceAbi")]
    public interface IServiceAbi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAbi/GetData", ReplyAction="http://tempuri.org/IServiceAbi/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAbi/GetData", ReplyAction="http://tempuri.org/IServiceAbi/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAbi/GetCollaborateurs", ReplyAction="http://tempuri.org/IServiceAbi/GetCollaborateursResponse")]
        ClassesDAO.ServiceABI.Collaborateur[] GetCollaborateurs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAbi/GetCollaborateurs", ReplyAction="http://tempuri.org/IServiceAbi/GetCollaborateursResponse")]
        System.Threading.Tasks.Task<ClassesDAO.ServiceABI.Collaborateur[]> GetCollaborateursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAbi/addCollaborateur", ReplyAction="http://tempuri.org/IServiceAbi/addCollaborateurResponse")]
        string addCollaborateur(ClassesDAO.ServiceABI.Collaborateur newCollaborateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAbi/addCollaborateur", ReplyAction="http://tempuri.org/IServiceAbi/addCollaborateurResponse")]
        System.Threading.Tasks.Task<string> addCollaborateurAsync(ClassesDAO.ServiceABI.Collaborateur newCollaborateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAbi/GetContratsCollaborateur", ReplyAction="http://tempuri.org/IServiceAbi/GetContratsCollaborateurResponse")]
        ClassesDAO.ServiceABI.ContratType[] GetContratsCollaborateur(string matricule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAbi/GetContratsCollaborateur", ReplyAction="http://tempuri.org/IServiceAbi/GetContratsCollaborateurResponse")]
        System.Threading.Tasks.Task<ClassesDAO.ServiceABI.ContratType[]> GetContratsCollaborateurAsync(string matricule);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAbiChannel : ClassesDAO.ServiceABI.IServiceAbi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAbiClient : System.ServiceModel.ClientBase<ClassesDAO.ServiceABI.IServiceAbi>, ClassesDAO.ServiceABI.IServiceAbi {
        
        public ServiceAbiClient() {
        }
        
        public ServiceAbiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAbiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAbiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAbiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ClassesDAO.ServiceABI.Collaborateur[] GetCollaborateurs() {
            return base.Channel.GetCollaborateurs();
        }
        
        public System.Threading.Tasks.Task<ClassesDAO.ServiceABI.Collaborateur[]> GetCollaborateursAsync() {
            return base.Channel.GetCollaborateursAsync();
        }
        
        public string addCollaborateur(ClassesDAO.ServiceABI.Collaborateur newCollaborateur) {
            return base.Channel.addCollaborateur(newCollaborateur);
        }
        
        public System.Threading.Tasks.Task<string> addCollaborateurAsync(ClassesDAO.ServiceABI.Collaborateur newCollaborateur) {
            return base.Channel.addCollaborateurAsync(newCollaborateur);
        }
        
        public ClassesDAO.ServiceABI.ContratType[] GetContratsCollaborateur(string matricule) {
            return base.Channel.GetContratsCollaborateur(matricule);
        }
        
        public System.Threading.Tasks.Task<ClassesDAO.ServiceABI.ContratType[]> GetContratsCollaborateurAsync(string matricule) {
            return base.Channel.GetContratsCollaborateurAsync(matricule);
        }
    }
}
