//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratTypeE
    {
        internal int idContratE { get; set; }
        internal System.DateTime dateDebutE { get; set; }
        internal string qualificationE { get; set; }
        internal string statutE { get; set; }
        internal decimal salaireE { get; set; }
        internal Nullable<System.DateTime> finReelleE { get; set; }
    
        public virtual CollaborateursE CollaborateurEntity { get; set; }
    }
}
